### ISSUE TITLE
Add antialiasing for rounded corners

### ISSUE THREAD

**Issue by Nickelony** [torchgm/RoundedTB#69] opened 2021-10-17 12:54 UTC
![image](https://user-images.githubusercontent.com/20436882/137627991-07558c71-f167-4625-8865-07ea138c942d.png)

It'd be very nice to have these corners smoothened out really.

**Comment by torchgm** [comment] 2021-10-17 14:33
Duplicate of #4; as of right now I don't have a solution to this I'm afraid, I can't do anything to AA the edges. If I suddenly stumble upon a way to do so however then it will be implemented.

**Closed by torchgm** 2021-10-17 14:33 UTC
