### ISSUE TITLE
Feature Suggestion: Make windows appear behind taskbar

### ISSUE THREAD

**Issue by Dylan734** [torchgm/RoundedTB#9] opened 2021-06-15 06:20 UTC
Hey there, great work on this project. I would like to suggest an option for windows to appear behind the taskbar as it looks cleaner.

From this:
![image](https://user-images.githubusercontent.com/38373357/122002427-4cd1fd80-cde4-11eb-88f8-396297b0f23f.png)

To this:
![image](https://user-images.githubusercontent.com/38373357/122002489-65421800-cde4-11eb-94d8-7312cd22e373.png)

**Comment by torchgm** [comment] 2021-06-15 07:32
I'm not 100% sure if this is reliably possible due to how the taskbar prevents other apps from messing around with it, but I can look into it. This would also mean that the taskbar interferes with certain UI controls at the bottom of any given window. In such a scenario I'd recommend using Windows' built-in "Automatically hide the taskbar" options (in Settings > Personalisation > Taskbar). 

I've already implemented preliminary support for this and it should work pretty well, just with a bit of flicker during the slideout animation. It should allow the taskbar to slide up over existing content when you need it, and disappear off the edge of the screen when you don't, without permanently obscuring stuff.

**Comment by Dylan734** [comment] 2021-06-15 18:54
Did not think of that issue, thanks for responding though. 

On a separate note, would it be possible to add the possibility for margins or corner radius to be set to a decimal number instead of just integers? Currently setting the margin to 2 or above would cut out the underline for open applications as shown below
Set to 1:
![image](https://user-images.githubusercontent.com/38373357/122107081-4461dd00-ce4d-11eb-85f3-24b29b5c0b40.png)
Set to 2 or more:
![image](https://user-images.githubusercontent.com/38373357/122107140-55aae980-ce4d-11eb-8936-1e38c7935b63.png)

Hopefully setting decimal numbers such as 1.5 would "fix" the issue enough

**Comment by enoversum** [comment] 2021-06-21 13:19
Well, being on Windows 11, RTB at least in my case doesn't work well anymore. It either shows no margins and roundings, or clips the whole bar and icons, see attached screenshot. When I hit the start button, the whole margin/rounded settings are being ignored. My margin is 4, my corner has 5px.
![GPaoJYcVvF](https://user-images.githubusercontent.com/8190174/122768647-18f34e00-d2a4-11eb-89f3-c489021d3346.jpg)

**Comment by torchgm** [comment] 2021-06-21 20:25
> On a separate note, would it be possible to add the possibility for margins or corner radius to be set to a decimal number instead of just integers?

@Dylan734 No. The measurements are provided in points ("logical pixels", effectively just 1px * scale factor). This is a hard limit when handling window regions (the way I manipulate the taskbar). In upcoming Windows versions, the indicator for open windows will likely be more prominent and this should no longer be an issue. If this isn't the case I might look into adding an alternative open-app indicator that replaces the stock functionality.


> Well, being on Windows 11, RTB at least in my case doesn't work well anymore. It either shows no margins and roundings, or clips the whole bar and icons, see attached screenshot.

@enoversum First-off, this should really be its own issue. Secondly, I don't recommend using, nor do I officially support unreleased leaked builds. Regardless, I can tell RoundedTB is doing everything it's intended to do and setting its region correctly, however it appears you've got another taskbar modification altering the appearance of the taskbar (or the dynamic acrylic updates are interfering). The reason the icons are getting cut off is because it is in fact cropping down the taskbar with an appropriate margin (the rounded corners are being applied too, see the Action Centre icon), but the background isn't updating.

Example of it working:
![image](https://user-images.githubusercontent.com/31840547/122823290-1231fe80-d2d7-11eb-8da1-832c9482eead.png)


This issue exists in Windows 10 as well and is caused by a bug in the Desktop Window Manager (DWM) that fails to redraw certain window elements after an update to their composition. There's nothing much I can do about this as far as I'm aware, but usually after clicking into and out of the taskbar or Start menu will "free" it up and it'll update to show the actual appearance. If I do find a reliable fix for this issue then it'll be implemented as soon as possible.

**Closed by torchgm** 2021-06-21 20:25 UTC

**Comment by enoversum** [comment] 2021-06-22 08:00
@torchgm I'm truly sorry, in a rush I didn't realise I posted to the wrong thread here (intended to leave my comment on the W11 one). I understand you don't support dev builds, and in fact I had used TranslucentTB (as you suggested in the other issue thread) in conjunction with your app. Apart from the blurry background, I can assure you the problems are the same without TranslucentTB unfortunately: It's either not showing any effect, or cutting the content like in my screenshot with very low values for margin and corners. Let's see what the new builds for W11 will bring when they are live officially. Thanks for the insight nonetheless 👍 !

**Comment by torchgm** [comment] 2021-06-22 11:53
@enoversum No worries! If you want to create a new issue with a screen recording with no other taskbar mods running & applying a margin of 2 and a corner radius of 16, then that'd be greatly beneficial into looking into it as I can't seem to replicate the issue.

**Comment by enoversum** [comment] 2021-06-22 12:08
@torchgm Funny thing is, this works when I apply it, and the next time I hit the Windows button, the modification disappears (no corners, no margin). At some point, when I return to my taskbar, the problem occurs again (see screenshot, happens with the values you requested). Then it disappears again. No other taskbar mods, there is only 'autohide' activated in the settings. If you want, I can still open a new issue, yet a screencast isn't possible due to it happening not in a reproducible, steady way, but rather seemingly random.
![8iSFtGq6rJ](https://user-images.githubusercontent.com/8190174/122921827-4521d400-d363-11eb-9efd-eafc32de8af5.jpg)

**Comment by torchgm** [comment] 2021-06-22 21:02
@enoversum If you could open a new issue that'd be great; autohide support is still very experimental so I'll probably wait for an official Insider build of co_release to drop before I can look into fixing this but it'd be good to have some evidence of the issue there for reference, thanks!
