### ISSUE TITLE
Auto-hide taskbar works, but not on a second display

### ISSUE THREAD

**Issue by TechStudent11** [torchgm/RoundedTB#151] opened 2022-01-10 18:43 UTC
I tried using the auto-hide taskbar setting in Windows (to give me more screen real-estate) and it worked! I can hover my house on the bottom to open. However, this isn't the case for my other display. I can see the taskbar (although one pixel of it) and but hovering won't make it pop up.

![image](https://user-images.githubusercontent.com/76978184/148821107-fc501173-5554-408d-a3a2-4e2f03b59ede.png)

I know this feature is pretty buggy right now, so I just thought I would bring this to your attention.

**Comment by torchgm** [comment] 2022-01-10 20:26
Yeah, a custom autohide is being developed because of the fact that it turns out it's impossible to make Windows' own autohide work correctly.

**Comment by TechStudent11** [comment] 2022-01-10 20:28
> Yeah, a custom autohide is being developed because of the fact that it turns out it's impossible to make Windows' own autohide work correctly.

ETA?

**Comment by torchgm** [comment] 2022-01-10 20:33
Absolutely no idea I'm afraid, life kinda sucks at the moment :c

I'm posting random updates on Twitter and in my Discord server though for the projects I'm working on if you're interested in following along

**Comment by TechStudent11** [comment] 2022-01-10 22:28
> Absolutely no idea I'm afraid, life kinda sucks at the moment :c

Okay. It's fine. Just take your time.

> I'm posting random updates on Twitter and in my Discord server though for the projects I'm working on if you're interested in following along

K, I'll check 'em out. I don't have a Twitter so don't expect to see me there. Cheers.

**Comment by TechStudent11** [comment] 2022-01-11 00:04
@torchgm Unrelated question: do you know of any program that allows you to get a MacOS like menubar up top? Just anything of the top of your head.

**Comment by Erisa** [comment] 2022-01-20 13:22
> @torchgm Unrelated question: do you know of any program that allows you to get a MacOS like menubar up top? Just anything of the top of your head.

GitHub issues aren't the place for unrelated questions.

Closing as duplicate of #36, continue auto-hide discussion there if you have more to say

**Closed by Erisa** 2022-01-20 13:22 UTC

**Comment by Erisa** [comment] 2022-01-20 13:33
> As I said, it works, just not on a second display. #36 is for one display. That doesn't make this a duplicate.
That issue is the place for tracking all auto-hide bugs, not just the main one of it not working on one display for people.
This can be seen by its title
> Automatically hiding the taskbar is buggy, flickers and doesn't respond correctly.

**Comment by TechStudent11** [comment] 2022-01-20 13:34
> That issue is the place for tracking all auto-hide bugs, not just the main one of it not working on one display for people.

Okay, then maybe pin it so that it isn't lost with the other issues?

**Comment by Erisa** [comment] 2022-01-20 13:35
> > That issue is the place for tracking all auto-hide bugs, not just the main one of it not working on one display for people.
> 
> Okay, then maybe pin it so that it isn't lost with the other issues?

Done
