### ISSUE TITLE
[Pre-release] Taskbar does not trim on left side with Dynamic Mode

### ISSUE THREAD

**Issue by Daksh-T** [torchgm/RoundedTB#41] opened 2021-09-18 06:23 UTC
![image](https://user-images.githubusercontent.com/25204941/133878550-007a14c5-0327-4b22-9631-8c7fbe4e7738.png)

When Dynamic Mode is turned on, the taskbar doesn't trim from the left side. I can reproduce this issue on Release P3.1 on Windows 11 Build 22000.194

**Comment by Daksh-T** [comment] 2021-09-18 06:32
I was able to 'fix' this issue by changing taskbar alignment from "Center" to "Left" and then back to "Left"

**Comment by torchgm** [comment] 2021-09-18 15:24
Ah yeah, this amazingly fun little bug! I should add this to the known bugs list (honestly just completely forgot about it). Just need to rearrange when I read from the registry is all, still thinks its left-aligned.

**Comment by chiphu** [comment] 2021-09-26 07:37
> I was able to 'fix' this issue by changing taskbar alignment from "Center" to "Left" and then back to "Center"

It works like a charm. Thank you for this tip!

**Comment by torchgm** [comment] 2021-09-27 07:30
So I'm now aware of why the issue exists but I'm not able to implement a reliable fix until I've refactored everything. This will hopefully be fixed in R4; I might try and add a patch for it in a smaller update, but considering its a one-time thing that can be fixed incredibly easily it's not high priority.

**Comment by torchgm** [comment] 2021-11-16 12:38
This is *supposed* to be fixed in R3.1 but a couple of people have mentioned it still occurs which is amazing fun.

**Comment by Daksh-T** [comment] 2021-11-16 13:48
Maybe it's occuring on some builds only?

**Comment by Erisa** [comment] 2022-01-20 14:11
The cause was eventually found: https://github.com/torchgm/RoundedTB/issues/114#issuecomment-977258164

Going to close this in favour of the pinned #98 - hopefully this should be addressed in the next release, and you can watch that issue for updates.

**Closed by Erisa** 2022-01-20 14:11 UTC
Labels: bug, duplicate, prerelease

**Comment by Frosty372** [comment] 2022-04-10 04:08
> I was able to 'fix' this issue by changing taskbar alignment from "Center" to "Left" and then back to "Center"

Thanks a lot. I stopped using this app due to this bug but now it looks amazing.

**Comment by joshthehappy** [comment] 2023-06-19 19:06
> I was able to 'fix' this issue by changing taskbar alignment from "Center" to "Left" and then back to "Center"

Thanks, works fine on Windows Pro, but my Lenovo tablet PC had this exact issue and that fixed it.
