### ISSUE TITLE
Don't work if "Automatically hide the taskbar" checked

### ISSUE THREAD

**Issue by lanzhiquan** [torchgm/RoundedTB#119] opened 2021-11-26 22:12 UTC
<img width="499" alt="1" src="https://user-images.githubusercontent.com/11311878/143658276-07a52bc0-9944-43e9-b501-61747fbb8914.png">

**Comment by torchgm** [comment] 2021-11-26 22:32
Duplicate of #117

**Closed by torchgm** 2021-11-26 22:32 UTC
