### ISSUE TITLE
RoundedTB doesn't work with Auto-hide Taskbar 

### ISSUE THREAD

**Issue by Qubisted** [torchgm/RoundedTB#103] opened 2021-11-16 02:03 UTC
When enabling dynamic mode and auto-hide taskbar, the new dock/taskbar does not show up on hover

**Comment by torchgm** [comment] 2021-11-16 12:03
Duplicate of too many issues to count but yep this isn't supported at the moment (and never really will be). Autohide directly interferes with how RoundedTB works. I'll be working on a custom autohide feature for a future update to address this.

**Closed by torchgm** 2021-11-16 12:03 UTC

**Comment by TechStudent11** [comment] 2021-12-09 22:43
@torchgm Is it in the canary version? If so, I would happily test it out. I would really love this feature!
