### ISSUE TITLE
Windows 11 auto hide flickering

### ISSUE THREAD

**Issue by zarthu** [torchgm/RoundedTB#54] opened 2021-09-30 07:14 UTC
Hey guys  there seems to be some flicking a few pixels tall at the bottom of the screen when using windows 11 auto hide with this application. No other taskbar mods are running. Has anyone found a fix or when this bug may be fixed? I am aware there is another post detailing this issue but it has been 25 days since. 

Incase anyone is wondering yes I installed the program through the windows store, I'm not quite sure if a new release has come out that perhaps has not made it onto the windows store.

**Comment by enoversum** [comment] 2021-09-30 08:26
Already mentioned here: https://github.com/torchgm/RoundedTB/issues/36#issuecomment-930284195

**Comment by torchgm** [comment] 2021-10-04 01:55
Closed as duplicate of #36, but summary is that Windows' autohide sucks, I won't ever be able to properly support it, and I'm working on a better replacement for it with more customisation.

**Closed by torchgm** 2021-10-04 01:55 UTC
