### ISSUE TITLE
RoundedTB  can't shorten the status bar completely.

### ISSUE THREAD

**Issue by QiQiWan** [torchgm/RoundedTB#93] opened 2021-11-13 03:48 UTC
When I applied the recommended configuration, the status bar at the bottom showed that it was not normal and it was not shortened correctly. 
As shown in the following figure
![image](https://user-images.githubusercontent.com/60660430/141604538-292ecd55-2ded-44fd-93e7-801b3cd1737d.png)

**Comment by torchgm** [comment] 2021-11-13 04:13
Duplicate of #41, #51, #60, #61, #62, #77 and #92 - the issue is fixed and will be available in the upcoming version R3.1

A workaround is to just set the taskbar icons to the left then back to the centre which will fix it indefinitely.

**Closed by torchgm** 2021-11-13 04:13 UTC

**Comment by kotx** [comment] 2021-11-19 02:18
Seems the taskbar doesn't resize correctly with Lively/TranslucentTB until the start menu is opened. Is this related?
![image](https://owo.whats-th.is/AUTNtiH.png)
