### ISSUE TITLE
Auto-hide Feature Integration Suggestion

### ISSUE THREAD

**Issue by ScienceGuy-66** [torchgm/RoundedTB#150] opened 2022-01-09 11:14 UTC
It would be good to have a feature which does auto hide and shows the taskbar when Desktop is focused and hides when window is focused.

**Comment by Erisa** [comment] 2022-01-20 13:24
Either duplicate of #36 or can be rolled into it regardless. Concerns and requests about auto-hide should go there for simplicity.

**Closed by Erisa** 2022-01-20 13:24 UTC
