### ISSUE TITLE
Make RoundedTB float over other windows.

### ISSUE THREAD

**Issue by chadify** [torchgm/RoundedTB#155] opened 2022-01-14 18:24 UTC
When Auto Hide the taskbar is enabled, if I open an app in the background, the taskbar remains floating, as the program I've clicked on I still haven't opened it.

One way to implement this feature would be creating a fake, hidden program opening, so that the taskbar always remain floating.

To make clear what I'm saying, in the Image below, I've opened Whatsapp but didn't open it in the foreground(as show by the amber accent color on it in the taskbar) so the taskbar remains floating:

![chrome_bj8u485b4E](https://user-images.githubusercontent.com/72332949/149566325-ba39bf93-4595-453b-9d1e-6bd752e2f1c4.png)

**Comment by torchgm** [comment] 2022-01-14 19:03
Autohide currently isn't supported at all (and never will be because the way it works directly conflicts with how RoundedTB works)

HOWEVER

I'm working on a custom autohide mode, and there will be an option to display the taskbar over your window at all times.

**Comment by Erisa** [comment] 2022-01-20 13:25
Duplicate of #36, continue discussion of concerns or requests for autohide over there

**Closed by Erisa** 2022-01-20 13:25 UTC
Labels: duplicate
