### ISSUE TITLE
White line below certain apps

### ISSUE THREAD

**Issue by luisfcosta** [torchgm/RoundedTB#127] opened 2021-12-02 14:31 UTC
This happens in windows explorer and office apps that I know of.
A minor thing for sure, but it does stand out in my oled tv/monitor.

![l1](https://user-images.githubusercontent.com/5273768/144441433-066d50c4-6364-40b9-89e2-d26f0bd007cb.jpg)
![l2](https://user-images.githubusercontent.com/5273768/144441438-38713c39-d742-4f22-b1e4-8aa4996dcab3.jpg)

**Comment by torchgm** [comment] 2021-12-02 15:30
Autohide isn't currently supported due to the *many* issues and outright incompatibilities it introduces - the next major update will introduce a new custom autohide mode that will address this.

**Comment by luisfcosta** [comment] 2021-12-06 10:56
Thank you! Thats great.
I've been using auto-hide so far with no issues besides this white line + the fact that activation is not possible if margins are set to > 0, but I guess you already know that.

**Comment by Erisa** [comment] 2022-01-20 13:23
Closing as duplicate of #36, continue any discussion of auto-hide problems there.

**Closed by Erisa** 2022-01-20 13:23 UTC
