### ISSUE TITLE
RoundedTB on Dynamic mode does not hide left side of Task Bar

### ISSUE THREAD

**Issue by Aadhino01** [torchgm/RoundedTB#145] opened 2021-12-31 03:53 UTC
![image](https://user-images.githubusercontent.com/96899083/147802325-388ec9c3-8cb5-4ffd-8021-dfbfc15ef413.png)

**Comment by TheDiamondGen** [comment] 2021-12-31 16:54
Settings > Personalization > Taskbar > taskbar behavior > Center to Left
And switch from Left to Center again
This is a known issue and has been posted many times.

**Comment by Aadhino01** [comment] 2022-01-01 02:34
> Settings > Personalization > Taskbar > taskbar behavior > Center to Left And switch from Left to Center again This is a known issue and has been posted many times.

Thank you so much it worked.

**Comment by Erisa** [comment] 2022-01-20 13:55
Can be fixed with the workaround above if anyone is coming across this issue.

Duplicate of #98 so closing

**Closed by Erisa** 2022-01-20 13:55 UTC
Labels: duplicate
