### ISSUE TITLE
Insider 22533 updates' new widget/weather button is hidden. 

### ISSUE THREAD

**Issue by LiemEldert** [torchgm/RoundedTB#158] opened 2022-01-19 14:20 UTC
The latest Insider build changes the widget button to left-align and also displays the weather. This gets hidden by RoundedTB.

**Comment by Erisa** [comment] 2022-01-19 18:43
Possible duplicate of #138

**Comment by torchgm** [comment] 2022-01-20 11:29
yup certainly seems to be a duplicate, lemme go answer that one instead

**Closed by torchgm** 2022-01-20 11:29 UTC
